DROP TABLE IF EXISTS JUROR;

CREATE TABLE IF NOT EXISTS JUROR (
	juror_id	INTEGER PRIMARY KEY AUTOINCREMENT,
	first_name	VARCHAR(30)		NOT NULL,
	last_name	VARCHAR(30) 	NOT NULL,
	birth_date	DATE			NOT NULL,
    ssn         CHAR(11),
	phone		VARCHAR(15)
);